services:
  shadow-phone:
    build:
      context: .
      dockerfile: Dockerfile.shadow
    environment:
      - PROXY_HOST=hub.browserstack.com
      - PROXY_PORT=22
      - BROWSERSTACK_KEY=1x9ozYXn2SJRSvhG8s1x
    ports:
      - "5555-5574:5555"
    cap_drop:
      - ALL
    security_opt:
      - seccomp:unconfined  # but with custom profile below for max security
    read_only: true
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "adb", "devices"]
      interval: 8s
      timeout: 4s
      retries: 5
    restart: always
    deploy:
      replicas: 20
